services:
  api-train:
    image: rakuten-api-train
    build:
      context: .
      dockerfile: docker/api-train/Dockerfile
    volumes:
      - rakuten_data:/app/data
      - rakuten_models:/app/models
      - rakuten_reports:/app/reports
      - rakuten_uploads:/app/uploads
    restart: "no"

  api-inference:
    image: rakuten-api-inference
#    deploy:
#      replicas: 3 # Lance 3 instances de ce service
    build:
      context: .
      dockerfile: docker/api-inference/Dockerfile
    depends_on:
      - api-train
    volumes:
      - rakuten_data:/app/data:ro
      - rakuten_models:/app/models:ro
      - rakuten_reports:/app/reports:ro
    restart: unless-stopped

  nginx:
    image: nginx:1.27-alpine
    container_name: rakuten-nginx
    depends_on:
      - api-inference
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./deployments/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./deployments/nginx/certs:/etc/nginx/certs:ro
    restart: unless-stopped

volumes:
  rakuten_data:
    name: rakuten_data
  rakuten_models:
    name: rakuten_models
  rakuten_reports:
    name: rakuten_reports
  rakuten_uploads:
    name: rakuten_uploads